blank_issues_enabled: false
contact_links:
  - name: Feature Request Template
    about: Request a new feature
    url: https://github.com/adeniyi-adeyemi/hello-world/issues/new?assignees=&labels=feature-request&template=feature_request.md&projects=adeniyi-adeyemi%2Fhello-world%2F1&title=test+issue
