name: Auto Assign to Project(s)

on:
  issues:
    types: [labeled]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
    - name: Assign issues with `feature-request` label to project 1
      uses: adeniyi-adeyemi/hello-world@1.2.1
      if: contains(github.event.issue.labels.*.name, 'feature-request')
      with:
        project: 'https://github.com/users/adeniyi-adeyemi/projects/1'
        column_name: 'Labeled'
